version: '3.8'
services:
  postgres-user:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - user_pg_data:/var/lib/postgresql/data

  postgres-todo:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_db
    ports:
      - "5434:5432"
    volumes:
      - todo_pg_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
    ports:
      - "4000:4000"
    depends_on:
      - postgres-user
    environment:
      DB_HOST: postgres-user
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: users_db

  todo-service:
    build:
      context: ./todo-service
    ports:
      - "4001:4001"
    depends_on:
      - postgres-todo
    environment:
      DB_HOST: postgres-todo
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: todos_db
      JWT_SECRET: your_jwt_secret_here

volumes:
  user_pg_data:
  todo_pg_data:
